version: "3.8"

services:
  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: stb-api-gateway
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - user-account
      - file-upload
    networks:
      - secure-bank

  user-account:
    build:
      context: ./user-account-service
      dockerfile: docker/Dockerfile
    container_name: stb-user-account
    volumes:
      - ./user-account-service:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    restart: always
    env_file:
      - ./user-account-service/.env
    depends_on:
      - user-account-db
      - redis
      - rabbitmq
    networks:
      - secure-bank

  user-account-db:
    image: postgres:15-bullseye
    container_name: stb-user-account-db
    volumes:
      - user_account_db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - secure-bank

  notification:
    build:
      context: ./notification-service
      dockerfile: docker/Dockerfile
    container_name: stb-notification
    volumes:
      - /app/node_modules
      - ./notification-service:/app:z
    restart: always
    env_file:
      - ./notification-service/.env
    depends_on:
      - rabbitmq
      - email-server
    networks:
      - secure-bank

  file-upload:
    build:
      context: ./file-upload-service
      dockerfile: docker/Dockerfile
    container_name: stb-file-upload
    volumes:
      - /app/node_modules
      - ./file-upload-service:/app:z
    restart: always
    env_file:
      - ./file-upload-service/.env
    depends_on:
      - aws-emulator
    networks:
      - secure-bank

  email-server:
    image: mailhog/mailhog:v1.0.0
    container_name: stb-email-server
    restart: always
    ports:
      - "8025:8025"
    networks:
      - secure-bank

  aws-emulator:
    image: localstack/localstack:2.1.0
    container_name: aws-emulator
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
    volumes:
      - aws-emulator-data:/tmp/localstack
    networks:
      - secure-bank

  redis:
    image: redis:7.0.0-alpine
    container_name: stb-redis
    networks:
      - secure-bank

  rabbitmq:
    image: rabbitmq:3.11.18-management
    container_name: stb-queue
    hostname: stb-queue
    ports:
      - 15672:15672
    env_file:
      "./.env"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - secure-bank

  search:
    build:
      context: ./search-service
      dockerfile: docker/Dockerfile
    container_name: stb-search
    volumes:
      - search-data:/usr/share/elasticsearch/data
    networks:
      - secure-bank

volumes:
  rabbitmq-data:
  user_account_db_data: {}
  media_volume:
  static_volume:
  aws-emulator-data:
  search-data:

networks:
    secure-bank:
      driver: bridge
