version: "3.8"

services:
  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: stb-api-gateway
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - user-account
      - file-upload
      - bank-account
    networks:
      - secure-bank

  user-account:
    build:
      context: ./user-account-service
      dockerfile: docker/Dockerfile
    container_name: stb-user-account
    volumes:
      - ./user-account-service:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    restart: always
    env_file:
      - ./user-account-service/.env
    expose:
      - "8000"
    depends_on:
      - user-account-db
      - redis
      - rabbitmq
      - search
    networks:
      - secure-bank

  user-account-db:
    image: postgres:15-bullseye
    container_name: stb-user-account-db
    volumes:
      - user_account_db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - "5432"
    networks:
      - secure-bank

  bank-account:
    restart: always
    build:
      context: ./bank-account-service
      dockerfile: docker/Dockerfile
    container_name: stb-bank-account
    expose:
      - "8080"
    volumes:
      - ./bank-account-service/src:/app/src
      - ./bank-account-service/pom.xml:/app/pom.xml
      - m2_cache:/root/.m2
    env_file:
      - ./bank-account-service/.env
    depends_on:
      - bank-account-db
    networks:
      - secure-bank

  bank-account-db:
    image: mysql:8.0
    container_name: stb-bank-account-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: bank_account_db
    volumes:
      - bank_account_db_data:/var/lib/mysql
    depends_on:
      - rabbitmq
    expose:
      - "3306"
    networks:
      - secure-bank

  notification:
    build:
      context: ./notification-service
      dockerfile: docker/Dockerfile
    container_name: stb-notification
    volumes:
      - /app/node_modules
      - ./notification-service:/app:z
    restart: always
    env_file:
      - ./notification-service/.env
    depends_on:
      - rabbitmq
      - email-server
    networks:
      - secure-bank

  file-upload:
    build:
      context: ./file-upload-service
      dockerfile: docker/Dockerfile
    container_name: stb-file-upload
    volumes:
      - /app/node_modules
      - ./file-upload-service:/app:z
    restart: always
    env_file:
      - ./file-upload-service/.env
    depends_on:
      - aws-emulator
    networks:
      - secure-bank

  email-server:
    image: mailhog/mailhog:v1.0.0
    container_name: stb-email-server
    restart: always
    ports:
      - "8025:8025"
    networks:
      - secure-bank

  aws-emulator:
    image: localstack/localstack:2.1.0
    container_name: aws-emulator
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - aws-emulator-data:/tmp/localstack
    networks:
      - secure-bank

  redis:
    image: redis:7.0.0-alpine
    container_name: stb-redis
    networks:
      - secure-bank

  rabbitmq:
    image: rabbitmq:3.11.18-management
    container_name: stb-queue
    hostname: stb-queue
    ports:
      - "15672:15672"
    env_file:
      "./.env"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - secure-bank

  search:
    build:
      context: ./search-service
      dockerfile: docker/Dockerfile
    container_name: stb-search
    volumes:
      - search-data:/usr/share/elasticsearch/data
    networks:
      - secure-bank

  db-dashboard:
    image: adminer:4.8.1
    container_name: stb-db-dashboard
    restart: always
    ports:
      - "8880:8080"
    networks:
      - secure-bank

volumes:
  rabbitmq-data:
  user_account_db_data: {}
  bank_account_db_data: {}
  media_volume:
  static_volume:
  aws-emulator-data:
  search-data:
  m2_cache:

networks:
    secure-bank:
      driver: bridge
