spring:
  datasource:
    url: jdbc:mysql://bank-account-db:3306/bank_account_db
    username: root
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

springdoc:
  swagger-ui:
      path: /api/v1/bank-account/api-docs

logging:
  level:
    root: info